INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Anatole France","a;208;C2;10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sainte-Anne","a;b") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Italie","a;N2;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Triangle","a;N2;161ex;13;TTZ;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clemenceau","a;N2;13;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("République","a;C1;67;N1;N2;N3;N4;N5;153ex;154ex;155ex;156ex;167ex;C2;C3;C4;C5;C6;11;TTZ;53;54;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Joliot-Curie - Chateaubriand","b;N5;201;202;C5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gros-Chêne","b;C3;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Courrouze","b;N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mabilais","b;N3;10;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Colombier","b;N3;C5;C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jules Ferry","b;C1;N5;10;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jacques Cartier","a;N2;C3;12;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Poterie","a;62;73;75;N2;173ex;175ex;214;C2;11;12;13;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Henri Fréville","a;72;74;79;80;N2;159ex;161ex;172ex;C3;13;32;37;TTZ;59;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pontchaillou","a") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Beaulieu - Université","b;N4;200;10;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Gayeulles","b;71;83;N5;14;51;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cleunay","b;N3;10;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gares","b;a;C1;63;C2;11;12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("J.F. Kennedy","a") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Charles de Gaulle","a;C1;N2;C3;TTZ;54;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Villejean-Université","a;65;68;76;77;78;81;82;N1;152ex;165ex;168ex;178ex;205;C4;12;14;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Atalante","b;N4;164ex;200;C4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Germain","b") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Jacques - Gaîté","b;N3;156ex;C6;C7;13;37;C7ex;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cesson - Viasilva","b;64;70;83;164ex;210;34;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Blosne","a;N2;13;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gériatrie","C1;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Domaine","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Villebois-Mareuil","C1;32;Ts22") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Saint-Hélier","C1;C2;11;Ts22;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Place Pasteur","C1;N5;C3;C5;12;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fossés","C1;N5;C3;12;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Metz Volney","C1;N5;32;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mirabeau","C1;201;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chantepie Eglise","C1;13;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Raison","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Laënnec","C1;C2;11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sévigné","C1;N5;C3;10;12;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Guéhenno","C1;N5;10;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cesson Hôpital Privé","C1;83;164ex;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chêne Germain","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chantepie Mairie","C1;13;34;Ts22") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mouézy","C1;11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gallet","C1;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Longs Champs","C1;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champs Blancs","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rosa Parks","C1;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Deux Ruisseaux","C1;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Loges","C1;13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("CARSAT","C1;214;C2;11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Landry","C1;Ts22") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Painlevé","C1;N5;14;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Assomption","C1;N5;200;201;202;204;206;216;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Turmel","C1;201;206;216;C5;14;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bouzat","C1;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Touche Annette","C1;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sauvaie","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Donzelot","C1;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Garenne","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Val d'Orson","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Rouge","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bel Air","62;73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Malinge","62;73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Martinière","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Solidor","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hallerais","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fosse Gauchère","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vern Eglise","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vern La Touche","62;73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bretonnière","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haute Abbaye","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Foyer Rennais","63;C5;245;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vallon","63;72;TTZ;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rabine","63;91;C7;C7ex;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Yves","63;C5;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Guyader","63") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Vaisserelle","63;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont-Réan","63;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Janais","63;72;TTZ;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Timonière","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont d'Ohin","64;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pâtis du Moulinet","64;83;200;220;221") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Village Collectivités","64;83;200;220;221") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gaudais","64;200;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Botrel","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lande","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Verdaudais","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Acigné Mairie","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Foyer","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Boulais","64;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Verger","64;200") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bouriande","64;83;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Berry","65;77;81;82;52;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont Amelin","65;234;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haute Rabine","65;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Reuvre","65;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parthenay Fontaine","65;165ex;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Duchesse Anne","65;234;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Renan","65;234;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chapitre","65;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Touche Champagne","65;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Placis de la Touche","65;165ex;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Carré Dumaine","65;77;243") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pacé Cimetière","65;77;234") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clos des Tilleuls","65;165ex;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parthenay Mairie","65;165ex;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Ponant","65;77;243") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourbonnais","65;77;81;82;N1;52;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Noë","65;165ex;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champs Péans","67;206;C6;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Taillis","67;167ex;206;C6;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Provence","67;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Moulin de Joué","67;210;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Tournebride","67;N4;167ex;206;210;C4;C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Monniais","67;206;214;14;34;38;Ts61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bordage","67;167ex;C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saules","67;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Robidou","67;N4;210;C4;C6;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cesson Gare","67;214;14;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Destiers","67;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Musée Beaux Arts","67;N4;C4;C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rond Point de Bray","67;214;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Turbanière","67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pâtis","67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mainguère","67;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Anjou","67;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Piletière","67;206") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Peupliers","67;14;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rigourdière","67;C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haut Grippé","67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champelé","67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Robiquette","68;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Léonard","68;78;178ex;C4;14;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Préfecture","68;78;168ex;178ex;C4;14;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gévezé Mairie","68;168ex;226;Ts75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Brosse","68") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Grand Quartier","68;78;178ex;C4;12;14;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cheval Blanc","68;168ex;226;Ts44;Ts75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Coualeuc","68;168ex;226;Ts44;Ts75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Prés Verts","68;168ex;226;Ts44;Ts75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Décoparc","68;224;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Flume","68;168ex;226;Ts75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cropy","70;71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lande Saint-Denis","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Giron","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Terrain des Sports","70;71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Oliverie","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Petite Hublais","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Touche Lambert","70;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chesnais","70;71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Tronchay","70;71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Tihouït","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cour Neuve","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourg","70;71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hôtel de Région","71;C5;14;51;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Betton Vallée","71;202;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("J. Sébastien Bach","71;202;222") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Laurent","71;83;202;C5;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Basse Robinais","71;202;222;223") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chevaigné Mairie","71;202;222;223") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Enseigne Abbaye","71;202;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Maison Blanche","71;202;51;39") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chopinais","71;202;222;223") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fonderies","71;202;222;223") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pommiers","71;202;222;223") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Betton Rue de Rennes","71;83") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Betton Centre","71;78;83;178ex;202;222;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gentilhommière","71;202;222") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chevaigné Gare","71;202;222;223") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Coubertin","72;212;213;13;TTZ;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Félix Eboué","72;C5;TTZ;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Collège Pôle Sud","72;91;172ex;Ts82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Renaissance","72;231") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bois Esnault","72;79;231") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Norvège","72;13;TTZ;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chartres Centre","72;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Auditoire","72;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cornouaille","72;172ex;Ts1;Ts13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mouton Blanc","72;79;231;235") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix aux Potiers","72;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vieux Bourg","72;172ex;Ts1;Ts13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Constant Mérel","72;172ex;Ts1;Ts13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fontaine Blanche","72;79;231") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rivaudière","72;79;231") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont-Péan Mairie","72;79;231") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chemin Vert","72;79;231") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parc de Loisirs","72;172ex;Ts1;Ts13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ferme des Peupliers","72;172ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Callouët","72;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Argoat","72;172ex;Ts1;Ts13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Caliorne","72;79;231") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Place de Kildare","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Corps-Nuds Gare","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vaugon","73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Armel Gare","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("ZA Bourgbarré","73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Launay Garnier","73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Huberdières","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Poste","73;75;232;Ts20") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lande du Jardin","73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Armel Eglise","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chêne Hervé","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Corps-Nuds Mairie","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Basse Erable","74;213;230;233;Ts51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Orgerblon","74") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Salle de Sports","74;161ex;213;230;233;Ts4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Motte","74;161ex;213;230;233;Ts51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haye Longue","74;Ts5;Ts6;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix du Pigeonnet","74;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ormes Blanches","74;213;230;Ts51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourgbarré Mairie","74;161ex;213;230;233;Ts4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Perelle","74;213;230;Ts51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Surcouf","74;213;230;Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Levant","74;213;Ts5;Ts6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Plardière","74;213;Ts6;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Centre de Loisirs","74;161ex;213;230;233;Ts4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Coteau","74;213;230;Ts6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Groupe Scolaire","74;213;230;Ts6;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Maillardière","75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Moulin","75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Grée Barel","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chêne Centenaire","75;175ex;Ts20") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Porte","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parc des Sports","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Menault","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Langlois","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Eclosel","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champs Bleus","76;153ex;227;Ts91;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mordelles Mairie","76;155ex;229;239;Ts8;55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Berger","76;N1;C4;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Colin","76;153ex;14;Ts91;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Tertre","76;227;Ts91;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vezin Centre","76;153ex;227;Ts46;Ts91;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Egalité","76") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Basch","76;165ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Acquêts","76;Ts32;Ts33") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gretay","76;155ex;229;239;Ts8;55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mordelles Eglise","76;155ex;229;239;Ts8;55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gaston Bardet","76;Ts33") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bouleaux","76;154ex;Ts33;54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("L'Autre Lieu","76;Ts32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mordelles Lilas","76;155ex;229;239;Ts8;Ts33;55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Merlin","76;14;Ts91;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lion d'Or","76;153ex;227;Ts46;Ts91;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mordelles Pâtis","76;155ex;229;239;Ts8;55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Opéra","77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Baiersdorf","77;225") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champalaune","77;225") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Beausoleil","77;225") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rive Ouest","77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ouessant","77;225") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Teillais","77;234") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pâtis Roussel","77;225") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("CHP Saint-Grégoire","78;178ex;204;C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Edonia","78;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jean-Paul II","78;178ex;223;224;225;234;243;Ts75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont Brand","78;178ex;222") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Kerguelen","78;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Paul-Emile Victor","78;204;32;39") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cité des Jardins","78;204;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Holywell","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Haute Plesse","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cerisaie","78;178ex;12;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Plesse","78;178ex;204;C2;12;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Alphasis","78;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Forge","78;178ex;204;C2;32;39") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Trégor","78;83;178ex;202;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Renaudais","78;178ex;222") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Betton Mairie","78;83;178ex;202;222;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chaperonnais","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mézières","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Laillé Eglise","79;80;231;Ts6;Ts12;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Châtaigneraie","79;80;231;Ts10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gingouillère","79;80;231;Ts10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Point du Jour","79;80;231;Ts11;Ts57") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Orée du Bois","79;80;231;Ts9") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Château d'Eau","80;235;Ts11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Simon","81;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Romillé Mairie","81;82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clayes Centre","81;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Romillé Collège","81;242;Ts71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Cour aux Pages","81;236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mettrie Templiers","81;82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Frères Aubert","81") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Langan Bourg","82;Ts71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chapelle-Chaussée","82;242;RPI-1;Ts75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bécherel Centre","82;242") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Miniac Eglise","82;242") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sévignière","82;242") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Omblais","83;202;222;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Joliot-Curie","83;201;204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pâtis Tatelin","83") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Thorigné Mairie","83;201;221;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Landelles","83;201;221;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Devant","83;202;222;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Curien","83;201;221;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Anne de Bretagne","83;201;221;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Brocéliande","83;202;223;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("ZA Saint-Sulpice","83;C4;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Longrais","83") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("ZA Bellevue","83") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Noë","90;159ex;C7;C7ex;245;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("DGA-MI","90;Ts12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lavoisier","90;91;229;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Victor Hugo","90;91;159ex;C7;C7ex;245;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Epalet","90;159ex;C7;C7ex;245;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("DGA-MI Nord","90") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pasteur","90;91;159ex;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bobinais","90;91;159ex;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bruz Centre","90;159ex;C7;C7ex;245;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Niguel","90;91;159ex;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bruz Gare","90;159ex;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Châteliers","90;91;159ex;C7;C7ex;245;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haut Launay","91;C7;C7ex;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vert Buisson","91;C7;C7ex;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cicé Blossac","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Guyomerais","91;Ts1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Monts Gaultier","91;Ts1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Taillebois","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Louis Texier","91;212;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chaussairie","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Doublé","91;59") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Petite Saudrais","91;212;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Centre","91;161ex;212;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Potiers","91;212;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mare de la Salle","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Place de Bretagne","N1;C2;C4;11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Salle","N1;C4;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Mail","N1;C4;11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chèques Postaux","N1;153ex;154ex;155ex;C4;11;53;54;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Guilloux","N1;C4;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Marbeuf","N1;C4;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Normandie","N1;12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Kennedy Guyenne","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Université","N1;C4;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bois Labbé","N1;C4;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Olympe de Gouges","N1;C4;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Languedoc","N1;C4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hôpital Sud","N2;13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ginguené","N2;C3;12;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Argonautes","N2;13;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Galicie","N2;12;13;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gare Sud Féval","N2;C3;12;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Voltaire","N3;10;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Maltière","N3;209;C6;C7;13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lande du Pont","N3;219;C7;C7ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cité Judiciaire","N3;C5;C6;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Guérinais","N3;10;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haut Bois","N3;C7;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Etangs","N3;219;C7;C7ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ker Lann","N3;219;C7;C7ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Dargent","N3;10;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Criée","N3;C5;C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Redon","N3;C6;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champion de Cicé","N3;10;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lilas","N3;13;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("St-Jacques Mairie","N3;C7;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Coeur de Campus","N3;219;C7;C7ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont de Strasbourg","N4;C4;C6;32;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Plaine de Baud","N4;C4;C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Beaulieu INSA","N4;C4;10;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Paul Bert","N4;C4;C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont de Châteaudun","N4;C4;C6;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Préales","N4;C4;C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("François Château","N4;C4;C6;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Beaulieu Chimie","N4;C4;10;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("IUT","N4;216;C4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Europe","N5;14;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Blizz","N5;C5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Exupéry","N5;14;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Trégain","N5;14;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parc Gayeulles","N5;C5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Maison Neuve","152ex;218;227;52;240") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Gilles Centre","152ex;218;227;52;240;Ts43") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont aux Moines","152ex;218;227;52;240;Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clos des Cerisiers","152ex;218;227;52;240;Ts43") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ile des Bois","152ex;218;227;52;240") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vigne","152ex;218;227;52;240;Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rochers","153ex;238;Ts37;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Village","153ex;238;240;Ts32;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont de Bretagne","153ex;154ex;155ex;53;54;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ville aux Archers","153ex;238;Ts37;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Place de la Mairie","153ex;238;Ts37;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("L'Hermitage Centre","153ex;238;240;Ts32;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clairefontaine","153ex;238;240;Ts32;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Platanes","154ex;Ts33;54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Trémelière","154ex;Ts33;54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Genêts","154ex;54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clos Joury","154ex;Ts33;54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Monod","154ex;237;238;239;240;Ts33;Ts66;Ts67;54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Melaine","154ex;Ts36;54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chêne Vert","154ex;Ts38;54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clos de la Vallée","154ex;54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Verger Eglise","155ex;Ts35;55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bouvrais","155ex;Ts35;55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Commeurec","156ex;209;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Blanche","156ex;211;229;237;241;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Avenir","156ex;211;229;237;241;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Calvaire","156ex;211;229;237;241;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Alfred de Musset","156ex;211;229;237;241;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix de Pierre","161ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Leuzières","161ex;212;Ts3;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ise","161ex;212;Ts3;Ts82;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Faucheux","161ex;212;Ts7;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Basses Noës","161ex;Ts7") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Côteaux","161ex;212;Ts3;Ts82;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jardin du Soleil","161ex;Ts7") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Belle Fontaine","164ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haut Trait","178ex;204;C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fouillard","201;221;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bocage","201;221;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Juteauderies","201;221;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Calendrou","201;221;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Portail","201;221;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Victoire","201;221;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haye Renaud Gare","202;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Housset","202;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Marronniers","202;51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ricoquais","204;223;C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Uttenreuth","204;208;C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Discalceat","204;C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Nobel","204;C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Camus","204;C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vivier Louis","204;C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Daguet","204;C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Mendès France","204;228;C2;12;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clotilde Vautier","204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("The Land","205") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vilaine","206;C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sports et Nature","206;C6;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hublais","206;C6;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cesson Piscine","206;214;Ts61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Métairies Chalotais","206;214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Coulée","206;216;C6;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mare Pavée","206;216;C6;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bois Perrin","206") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cesson Mairie","206") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fontenelle","206;216;C6;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Lacs","206;216;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cormier","206;216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("MFR Rabinardières","208") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Verte","209") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rablais Allende","209") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mermoz","209;C5;245;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jean Pont","209;13;37") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Collège Jean Moulin","209;219;C6;13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Collège Cleunay","211") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haie des Cognets","211;37") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Etangs d'Apigné","211") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Grippay","211;237;241;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Mulon","212;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Fleurie","212;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mail Lancé","212;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Paul Féval","212;Ts3;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Alexandre Gilois","212;Ts3;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Molène","212;Ts1;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Canada","212;213;C3;13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fort Joual","213;Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Frogerais","213;Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Télégraphe","213;Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Moc Souris","213;Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Petite Rochelle","213;Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sept Fours","213;Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Breillou","214;11;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Monnet","214;C2;11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourgueil","214;C2;11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ronceray","214;C2;11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Forum","214;11;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Ozanam","214;220;Ts61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gohier","214;C2;11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Veyettes","214;11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bas Village","214;11;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Charmilles","214;11;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chalotais","214;220;C6;34;Ts61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Petits Champs","216;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Dézerseul","216;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourgchevreuil","216;C6;34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Centre scolaire Pacé","218;226;227;236;Ts41;Ts43;Ts44;Ts45;Ts46") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Anita Conti","219;229;230;231;Ts4;Ts5;Ts6;Ts7;Ts9;Ts10;Ts11;Ts12;Ts13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parc Expo","219;13;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Médiathèque","219;C6;13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Aire du 8 Mai","219;229;230;231;Ts1;Ts3;Ts4;Ts5;Ts6;Ts7;Ts8;Ts9;Ts10;Ts11;Ts12;Ts13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jean Marin","219;C6;13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jean Jaurès","219;C6;13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Aire Libre","219;C6;13;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Abbé Grimault","219;C6;13;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Corbières","219;C7;C7ex;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Centre Météo","219;13;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Morinais","219;C6;13;37") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Brossolette","219;229;231;Ts4;Ts7;Ts9;Ts10;Ts11;Ts12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Madame","219;229;C7;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jules Vallès","219;13;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Sévigné","220;221") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cesson Collège","221;C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Château de Vaux","221;50") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fougerolle","224;226;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Silandière","224;226;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Chapelle Centre","224;226;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Belle Epine","224;226;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pierre Texier","224;226;228;52;Ts41") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Montgermont Mairie","224;226;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Viennais","224;226;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Métairie","224;226;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Métrie","224;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Courtines","224;226;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sénestrais","224;226;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Besneraie","224;226;228;52") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haie de Terre","227;Ts46;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fouaye","227;52;Ts43") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vallée","227;Ts46;Ts91;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Collège Saint-Paul","230;233;Ts5;Ts6;Ts51;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hauts de Gaudon","232") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vern Gare","232") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Collège Récipon","233;Ts4;Ts51;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clairville","236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Renardière","236") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Donelière","C2;12;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cimetière Nord","C2;12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pierre Legrand","C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Trois Croix","C2;12;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Lices","C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Piré","C2;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Descartes","C2;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Martin","C2;12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Touche","C2;10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Brest Verdun","C2;10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("TNB","C2;11;12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Calmette","C2;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haut Sancé","C2;11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Horizons","C2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourgeois","C2;32;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Monsieur Vincent","C2;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mahomat","237;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mare Doux","237;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haut Plessis","237;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Collège Brassens","237;238;240;Ts66;Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Moigné","237;Ts33;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Monts d'Arrée","C3;14;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Prairies","C3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Alma","C3;13;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Neruda","C3;14;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Condate","C3;14;32;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Morbihan","C3;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rochester","C3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rectorat","C3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Frères Moine","C3;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Patton","C3;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bellangerais","C3;14;32;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Garigliano","C3;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hôtel Dieu","C3;10;12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Suède","C3;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Houx Cité U","C3;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Volney","C3;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sacrés Coeurs","C3;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champs Manceaux","C3;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vincennes","C3;10;12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hautière","238;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("L'Hermitage Gare","238;Ts34;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Grippière","238;Ts37;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Piardière","238;Ts37;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cucillé - Frac","C4;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Longs Champs Est","C4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Becquerel","C4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Dulac","C4;12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Bréquigny","C5;13;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pilate","C5;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Thabor","C5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Héronière","C5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont de Nantes","C5;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Oberthur","C5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Durafour","C5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pigeon Blanc","C5;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gayeulles Piscine","C5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vitré Danton","C5;10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pressoirs","C5;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Vincent","C5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jeanne d'Arc","C5;10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Châteaudun","C5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Boberil","C5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Maison d'Accueil","C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Conwoïon","C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Coeur de Courrouze","C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Aéroport","C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jules Verne","C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jules Maniez","C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Germaine Tillion","C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Muguet","C6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gavrinis","C7;C7ex;245") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Montand","10;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vaneau","10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("George Sand","10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Porte de Cleunay","10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clinique La Sagesse","10;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Dinan","10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Récipon","10;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Beaulieu Cité U","10;14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Legraverend","10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Musset Cité U","10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Balzac","10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("ZA L'Hermitière","235") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hamonais","235") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("L'Hermitière Village","235;Ts6;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Guilloux Lorient","11;54;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Marais","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Buisson","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cimetière de l'Est","11;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Serpette","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Servigné","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Trois Marches","11;54;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("ZI Ouest","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Papeteries","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Roazhon Park","11;14;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lemaistre","11;54;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Erbonière","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Saëns","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pavie","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Kerviler","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Berthault","11;54;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pré Garel","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Géniaux","11;14;TTZ;54;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jardin Moderne","11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Langevin","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Harpe","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bigot de Préameneu","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Leray","12;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Landrel","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parc Beauregard","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Malraux","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gide","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pologne","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Meynier","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Square de la Rance","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ormeaux","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cours Kennedy","12;14;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mandela","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lenoir","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Auberge de Jeunesse","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Châtillon","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sainte-Thérèse","12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Binquenais","13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Binquenais Collège","13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Combes","13;32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Torigné","13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rocade Sud","13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cucé","13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Val Blanc","13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hallouvry","13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Porte de Ker Lann","13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("25 Fusillés","13;37") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bréquigny Piscine","13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourgogne","13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("EDEFS","13") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Longs Prés","14;TTZ") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hélias","14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chambre Agriculture","14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Arts","14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Atalante Champeaux","14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Armorique","14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Villejean-Churchill","14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vitré Foulon","14") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chardonnet","32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Metz","32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Motte Brûlon","32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Alma Sud","32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Durafour Strasbourg","32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Kerfleury","32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Dantec","32") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Landes","34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Stade Belliard","34") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bellevue","37") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Reuzerais","37") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Maffeys","37") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Pâtis","37") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Auriol","37") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ménouriais","38;Ts61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pinault","52;243") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pie Neuve","52;243;Ts43") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Docteur Léon","52;243;Ts43") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Touche Milon","52;243;Ts43") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vizeule","52;Ts41") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Nominoë","52;243") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Ignon","239;55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vivier des Bois","239;55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Grande Fontaine","239;55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Morvan Lebesque","241;Ts32;Ts34;Ts35;Ts37;Ts38;Ts36") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Collège St-Yves","241;Ts32;Ts33;Ts34;Ts35;Ts37;Ts38;Ts36") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Abords Rouvray","Ts1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Couasmes","Ts1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Noyal La Touche","Ts1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Launay Hyon","Ts1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cours d'A Haut","Ts3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont de l'Ise","Ts3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont","Ts3;Ts82;61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Douazel","Ts3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Horizon","Ts3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Abords Launay","Ts3;Ts82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lande de Pinçon","Ts3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lotissement du Moulin","Ts3;Ts82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Fretais","Ts4;Ts51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clos Vezins","Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Violais","Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Rochelle","Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Abords Lauriais","Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Barre","Ts5;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Montheleu","Ts6;Ts53;Ts57") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Blés d'Or","Ts6") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bossardière","Ts6;Ts53;Ts57") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Belle Etoile","Ts6;Ts53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ du Puit","Ts7") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Louvrel","Ts7") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("ZA Le Rachat","Ts9;Ts55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gripay","Ts9;Ts57") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("L'Oie","Ts9;Ts57") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Boulais Pochetière","Ts9;Ts55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Couais","Ts9;Ts57") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Touche Audienne","Ts10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Martigné","Ts10") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("L'Ardrais","Ts11") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Estuaires","Ts11;Ts57") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bout de Lande","Ts11;Ts57") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Roche Marguerite","Ts12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Nid","Ts12") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Epron","Ts20") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Gobigné","Ts20") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Tertronais","Ts20") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("L'Ourmais","Ts20") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Planche","Ts22") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Rouget","Ts32;Ts66") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cherterie","Ts32;Ts66") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont Harel","Ts32;Ts66") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Barberais","Ts33;54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rue de Montfort","Ts34;Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rue de Pacé","Ts34;Ts66") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lemordant","Ts34;Ts66") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("ESAT La Hautière","Ts34;Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Monbusson","Ts35") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Breil","Ts35") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Lande Basse","Ts35") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Richeudais","Ts38") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Belle Arrivée","Ts38") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Haute Barre","Ts38") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bersandières","Ts41") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Quatre Vents","Ts41") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Izé","Ts41") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Boussardière","Ts41") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chêne aux Dames","Ts41") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Thébaudière","Ts41") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ardriers","Ts43;Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Etang de la Motte","Ts43;Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Houdinais","Ts43;Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Roheu","Ts43;Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Beauvais","Ts44") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Hyptais","Ts44") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vieux Moulin","Ts44") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Brosse Allée","Ts45") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Montaigu","Ts45") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Forge Mallet","Ts45") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lande de Villé","Ts45") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gévezé Clairville","Ts45") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Foucherais","Ts45") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Huchetais","Ts45") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fresnot","Ts46") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sorinais","Ts46") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bas Sommier","Ts46") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pré Hervy","Ts46") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont du Gué","Ts51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Cruaux","Ts51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Rocher","Ts51") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Cleux","Ts55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Vallées","Ts55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Laillé Collège","Ts55;Ts57") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rouesnais Sud","Ts55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Corbinais","Ts55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rouesnais Nord","Ts55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Touche sur Roche","Ts61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Salmondière","Ts61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Prieuré Forge","Ts61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pierre Blanche","Ts66") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Verdais","Ts66") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Frétillé","Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haute Fresnais","Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Résidence Janais","Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Hubert","Ts67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bécherel Ecole","RPI-1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Rhé","Ts71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bois Menu","Ts71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chauvrais Malabry","Ts71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rouaudière","Ts71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Collège Rosa Parks","Ts91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Noël","Ts91;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Petit Champeaux","Ts91;53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ville Noublée","Ts36") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Bordes","Ts36") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Roch","Ts36") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bintin","Ts36") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Noë Biche","53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Agrocampus","53") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Noë Diolé","54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Plessix Saucourt","54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Pins","54") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont d'Avoine","54;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Liberté","54;55;56") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gerhoui","55") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parc d'Activités","61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Petit Beaulieu","61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bray","61") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hil-Bintinais","61") ON CONFLICT DO NOTHING;
