INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Anatole France","a;208") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sainte-Anne","a;b") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Italie","a;N2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Triangle","a;N2;161ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clemenceau","a;N2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("République","a;C1;67;N1;N2;N3;N4;N5;153ex;154ex;155ex;156ex;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Joliot-Curie - Chateaubriand","b;N5;201;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gros-Chêne","b") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Courrouze","b;N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mabilais","b;N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Colombier","b;N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jules Ferry","b;C1;N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jacques Cartier","a;N2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Poterie","a;62;73;75;N2;173ex;175ex;214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Henri Fréville","a;72;74;79;80;N2;159ex;161ex;172ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pontchaillou","a") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Beaulieu - Université","b;N4;200") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Gayeulles","b;71;83;N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cleunay","b;N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gares","b;a;C1;63") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("J.F. Kennedy","a") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Charles de Gaulle","a;C1;N2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Villejean-Université","a;65;68;76;77;78;81;82;N1;152ex;165ex;168ex;178ex;205") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Atalante","b;N4;164ex;200") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Germain","b") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Jacques - Gaîté","b;N3;156ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cesson - Viasilva","b;64;70;83;164ex;210") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Blosne","a;N2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gériatrie","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Domaine","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Villebois-Mareuil","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Saint-Hélier","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Place Pasteur","C1;N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fossés","C1;N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Metz Volney","C1;N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mirabeau","C1;201") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chantepie Eglise","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Raison","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Laënnec","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sévigné","C1;N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Guéhenno","C1;N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cesson Hôpital Privé","C1;83;164ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chêne Germain","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chantepie Mairie","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mouézy","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gallet","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Longs Champs","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champs Blancs","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rosa Parks","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Deux Ruisseaux","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Loges","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("CARSAT","C1;214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Landry","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Painlevé","C1;N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Assomption","C1;N5;200;201;202;204;206;216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Turmel","C1;201;206;216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bouzat","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Touche Annette","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sauvaie","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Donzelot","C1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Garenne","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Val d'Orson","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Rouge","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bel Air","62;73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Malinge","62;73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Martinière","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Solidor","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hallerais","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fosse Gauchère","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vern Eglise","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vern La Touche","62;73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bretonnière","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haute Abbaye","62") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Foyer Rennais","63") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vallon","63;72") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rabine","63;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Yves","63") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Guyader","63") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Vaisserelle","63;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont-Réan","63;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Janais","63;72") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Timonière","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont d'Ohin","64;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pâtis du Moulinet","64;83;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Village Collectivités","64;83;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gaudais","64;200") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Botrel","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lande","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Verdaudais","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Acigné Mairie","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Foyer","64;164ex;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Boulais","64;200;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Verger","64;200") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bouriande","64;83") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Berry","65;77;81;82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont Amelin","65") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haute Rabine","65") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Reuvre","65") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parthenay Fontaine","65;165ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Duchesse Anne","65") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Renan","65") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chapitre","65") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Touche Champagne","65") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Placis de la Touche","65;165ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Carré Dumaine","65;77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pacé Cimetière","65;77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clos des Tilleuls","65;165ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parthenay Mairie","65;165ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Ponant","65;77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourbonnais","65;77;81;82;N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Noë","65;165ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champs Péans","67;206") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Taillis","67;167ex;206") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Provence","67;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Moulin de Joué","67;210") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Tournebride","67;N4;167ex;206;210") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Monniais","67;206;214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bordage","67;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saules","67;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Robidou","67;N4;210") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cesson Gare","67;214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Destiers","67;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Musée Beaux Arts","67;N4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rond Point de Bray","67;214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Turbanière","67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pâtis","67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mainguère","67;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Anjou","67;167ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Piletière","67;206") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Peupliers","67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rigourdière","67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haut Grippé","67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champelé","67") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Robiquette","68") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Léonard","68;78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Préfecture","68;78;168ex;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gévezé Mairie","68;168ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Brosse","68") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Grand Quartier","68;78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cheval Blanc","68;168ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Coualeuc","68;168ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Prés Verts","68;168ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Décoparc","68") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Flume","68;168ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cropy","70;71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lande Saint-Denis","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Giron","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Terrain des Sports","70;71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Oliverie","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Petite Hublais","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Touche Lambert","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chesnais","70;71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Tronchay","70;71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Tihouït","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cour Neuve","70") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourg","70;71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hôtel de Région","71") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Betton Vallée","71;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("J. Sébastien Bach","71;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Laurent","71;83;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Basse Robinais","71;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chevaigné Mairie","71;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Enseigne Abbaye","71;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Maison Blanche","71;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chopinais","71;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fonderies","71;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pommiers","71;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Betton Rue de Rennes","71;83") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Betton Centre","71;78;83;178ex;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gentilhommière","71;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chevaigné Gare","71;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Coubertin","72;212;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Félix Eboué","72") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Collège Pôle Sud","72;91;172ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Renaissance","72") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bois Esnault","72;79") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Norvège","72") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chartres Centre","72;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Auditoire","72;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cornouaille","72;172ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mouton Blanc","72;79") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix aux Potiers","72") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vieux Bourg","72;172ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Constant Mérel","72;172ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fontaine Blanche","72;79") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rivaudière","72;79") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont-Péan Mairie","72;79") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chemin Vert","72;79") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parc de Loisirs","72;172ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ferme des Peupliers","72;172ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Callouët","72;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Argoat","72;172ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Caliorne","72;79") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Place de Kildare","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Corps-Nuds Gare","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vaugon","73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Armel Gare","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("ZA Bourgbarré","73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Launay Garnier","73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Huberdières","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Poste","73;75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lande du Jardin","73") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Armel Eglise","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chêne Hervé","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Corps-Nuds Mairie","73;173ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Basse Erable","74;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Orgerblon","74") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Salle de Sports","74;161ex;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Motte","74;161ex;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haye Longue","74") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix du Pigeonnet","74;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ormes Blanches","74;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourgbarré Mairie","74;161ex;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Perelle","74;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Surcouf","74;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Levant","74;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Plardière","74;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Centre de Loisirs","74;161ex;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Coteau","74;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Groupe Scolaire","74;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Maillardière","75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Moulin","75") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Grée Barel","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chêne Centenaire","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Porte","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parc des Sports","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Menault","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Langlois","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Eclosel","75;175ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champs Bleus","76;153ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mordelles Mairie","76;155ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Berger","76;N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Colin","76;153ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Tertre","76") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vezin Centre","76;153ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Egalité","76") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Basch","76;165ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Acquêts","76") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gretay","76;155ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mordelles Eglise","76;155ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gaston Bardet","76") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bouleaux","76;154ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("L'Autre Lieu","76") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mordelles Lilas","76;155ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Merlin","76") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lion d'Or","76;153ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mordelles Pâtis","76;155ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Opéra","77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Baiersdorf","77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champalaune","77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Beausoleil","77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rive Ouest","77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ouessant","77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Teillais","77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pâtis Roussel","77") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("CHP Saint-Grégoire","78;178ex;204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Edonia","78") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jean-Paul II","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont Brand","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Kerguelen","78") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Paul-Emile Victor","78;204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cité des Jardins","78;204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Holywell","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Haute Plesse","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cerisaie","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Plesse","78;178ex;204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Alphasis","78") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Forge","78;178ex;204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Trégor","78;83;178ex;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Renaudais","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Betton Mairie","78;83;178ex;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chaperonnais","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mézières","78;178ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Laillé Eglise","79;80") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Châtaigneraie","79;80") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gingouillère","79;80") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Point du Jour","79;80") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Orée du Bois","79;80") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Château d'Eau","80") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Simon","81") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Romillé Mairie","81;82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clayes Centre","81") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Romillé Collège","81") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Cour aux Pages","81") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mettrie Templiers","81;82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Frères Aubert","81") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Langan Bourg","82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chapelle-Chaussée","82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bécherel Centre","82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Miniac Eglise","82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sévignière","82") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Omblais","83;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Joliot-Curie","83;201;204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pâtis Tatelin","83") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Thorigné Mairie","83;201") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Landelles","83;201") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Devant","83;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Curien","83;201") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Anne de Bretagne","83;201") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Brocéliande","83;202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("ZA Saint-Sulpice","83") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Longrais","83") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("ZA Bellevue","83") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Noë","90;159ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("DGA-MI","90") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lavoisier","90;91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Victor Hugo","90;91;159ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Epalet","90;159ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("DGA-MI Nord","90") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pasteur","90;91;159ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bobinais","90;91;159ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bruz Centre","90;159ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Niguel","90;91;159ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bruz Gare","90;159ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Châteliers","90;91;159ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haut Launay","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vert Buisson","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cicé Blossac","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Guyomerais","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Monts Gaultier","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Taillebois","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Louis Texier","91;212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chaussairie","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Doublé","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Petite Saudrais","91;212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Centre","91;161ex;212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Potiers","91;212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mare de la Salle","91") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Place de Bretagne","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Salle","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Mail","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chèques Postaux","N1;153ex;154ex;155ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Guilloux","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Marbeuf","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Normandie","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Kennedy Guyenne","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Université","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bois Labbé","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Olympe de Gouges","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Languedoc","N1") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hôpital Sud","N2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ginguené","N2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Argonautes","N2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Galicie","N2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gare Sud Féval","N2") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Voltaire","N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Maltière","N3;209") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lande du Pont","N3;219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cité Judiciaire","N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Guérinais","N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haut Bois","N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Etangs","N3;219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ker Lann","N3;219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Dargent","N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Criée","N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Redon","N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champion de Cicé","N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lilas","N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("St-Jacques Mairie","N3") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Coeur de Campus","N3;219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont de Strasbourg","N4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Plaine de Baud","N4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Beaulieu INSA","N4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Paul Bert","N4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont de Châteaudun","N4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Préales","N4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("François Château","N4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Beaulieu Chimie","N4") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("IUT","N4;216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Europe","N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Blizz","N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Exupéry","N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Trégain","N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parc Gayeulles","N5") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Maison Neuve","152ex;218") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Gilles Centre","152ex;218") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont aux Moines","152ex;218") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clos des Cerisiers","152ex;218") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ile des Bois","152ex;218") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vigne","152ex;218") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rochers","153ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Village","153ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Pont de Bretagne","153ex;154ex;155ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ville aux Archers","153ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Place de la Mairie","153ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("L'Hermitage Centre","153ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clairefontaine","153ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Platanes","154ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Trémelière","154ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Genêts","154ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clos Joury","154ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Monod","154ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Saint-Melaine","154ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chêne Vert","154ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clos de la Vallée","154ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Le Verger Eglise","155ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bouvrais","155ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Commeurec","156ex;209") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Blanche","156ex;211") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Avenir","156ex;211") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Calvaire","156ex;211") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Alfred de Musset","156ex;211") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix de Pierre","161ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Leuzières","161ex;212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ise","161ex;212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Faucheux","161ex;212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Basses Noës","161ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Côteaux","161ex;212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jardin du Soleil","161ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Belle Fontaine","164ex") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haut Trait","178ex;204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fouillard","201") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bocage","201") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Juteauderies","201") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Calendrou","201") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Portail","201") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Victoire","201") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haye Renaud Gare","202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Housset","202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Marronniers","202") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ricoquais","204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Uttenreuth","204;208") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Discalceat","204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Nobel","204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Camus","204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vivier Louis","204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Daguet","204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Mendès France","204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Clotilde Vautier","204") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("The Land","205") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Vilaine","206") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sports et Nature","206") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Hublais","206") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cesson Piscine","206;214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Métairies Chalotais","206;214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("La Coulée","206;216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mare Pavée","206;216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bois Perrin","206") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cesson Mairie","206") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fontenelle","206;216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Les Lacs","206;216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Cormier","206;216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("MFR Rabinardières","208") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Verte","209") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Rablais Allende","209") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mermoz","209") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jean Pont","209") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Collège Jean Moulin","209;219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Collège Cleunay","211") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Haie des Cognets","211") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Etangs d'Apigné","211") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Grippay","211") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Champ Mulon","212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Fleurie","212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Mail Lancé","212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Paul Féval","212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Alexandre Gilois","212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Molène","212") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Canada","212;213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Fort Joual","213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Frogerais","213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Télégraphe","213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Moc Souris","213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Petite Rochelle","213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Sept Fours","213") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Breillou","214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Monnet","214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourgueil","214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Ronceray","214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Forum","214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Ozanam","214;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Gohier","214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Veyettes","214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bas Village","214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Charmilles","214") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Chalotais","214;220") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Petits Champs","216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Dézerseul","216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Bourgchevreuil","216") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Centre scolaire Pacé","218") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Anita Conti","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Parc Expo","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Médiathèque","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Aire du 8 Mai","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jean Marin","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jean Jaurès","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Aire Libre","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Abbé Grimault","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Corbières","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Centre Météo","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Morinais","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Brossolette","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Croix Madame","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Jules Vallès","219") ON CONFLICT DO NOTHING;
INSERT INTO rennes_star_lines(nomarret,lignes) VALUES("Lycée Sévigné","220") ON CONFLICT DO NOTHING;
